total_batch_size: 393216
B: 16
T: 1024
max_steps: 20000

num_samples_per_interval: 5
sample_max_length: 50
sample_prompt: "Hello, I'm a language model,"
sample_interval: 2500

save_interval: 5000
hellaswag_eval_interval: 500
hellaswag_eval_limit: null

max_lr: 0.001
min_lr: 0.0001
warmup_steps: 300
weight_decay: 0.1
